version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Maps123!
      POSTGRES_DB: maps
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5001:5001
    depends_on:
      - db
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
